name: Deploy Subgraph to Dev

on:
  push:
    branches:
      - main

# Declare default permissions as read only.
permissions: read-all

jobs:
  deploy:
    uses: .github/workflows/deploy-template.yml
    with:
      environment: dev
      subgraphId: rootstockcollective-governance-dev
      networkName: rootstock-testnet
      graphUrl: https://api.studio.thegraph.com/deploy/
      environmentName: dev
    secrets: inherit

